<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Pinku" name="subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest" tests="4" failures="1" timestamp="2024-07-29T02:03:44 IST" time="64.512" errors="0">
  <testcase name="loginErrorValidation" time="4.728" classname="subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect email password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <system-out/>
  <testcase name="loginErrorValidation" time="5.508" classname="subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <system-out/>
  <testcase name="productErrorValidation" time="19.924" classname="subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest"/>
  <system-out/>
  <testcase name="productErrorValidation" time="34.352" classname="subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <system-out/>
</testsuite> <!-- subhankar.SeleniumFrameworkDesign.tests.ErrorValidationsTest -->
